//@no-log
POST http://{{host}}:8181/login
Accept: */*
Accept-Charset: UTF-8
Cache-Control: no-cache
Content-Type: application/json

{
  "username": "admin",
  "password": "cocacola#1"
}
> {%
client.global.set('auth_token', response.body.token);
client.test("Headers option exists", function() {
        client.assert(response.body.hasOwnProperty("token"), "Cannot find 'token' field in response");
    });
%}

###
POST http://{{host}}:8181/protected/v1/crud/report/get
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

{
  "_id": "5d64e7bbf26cd07b8e12cb7d"
}

###

POST http://{{host}}:8181/protected/v1/crud/report/put
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

{
  "branch": "5d3775e442105000ccc036ee",
  "user": "5d5271865e97dc0971b6efe0",
  "date": 1566864000000,
  "loanersPawned": 3.0,
  "loanersBought": 2.0,
  "loanedRub": 1000.0,
  "repayedRub": 200.0,
  "percentRecieved": 100.0,
  "goldBought": 30.0,
  "goldSold": 20.0,
  "silverBought": "0",
  "silverSold": "0",
  "diamondBought": "0",
  "diamondSold": "0",
  "goodsBought": 1000.0,
  "goodsSold": "0",
  "cashboxEvening": 3000.0,
  "tradesActive": 10.0,
  "goldTradeSum": 10000.0,
  "goldTradeWeight": 300.0,
  "silverTradeSum": "0",
  "silverTradeWeight": "0",
  "diamondsTradeWeight": "0",
  "goodsTradeSum": "0",
  "expenses": [
    {
      "id": "1566893989655",
      "name": "такси",
      "sum": 1000.0
    }
  ],
  "auctionAmount": "0"
}

###

GET http://{{host}}:8181/protected/v1/newReport
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

{}

###

POST http://{{host}}:8181/protected/v1/crud/report/get/previous
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

{
  "reportId": "5d40b17014ce4a692cce08af"
}

###

POST http://{{host}}:8181/protected/v1/calculateDynamics
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

{
  "branchId": "5d3775e442105000ccc036ee",
  "reportDate": "1565038800000"
}

###

GET http://{{host}}:8181/protected/v1/statistics
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

###

GET http://{{host}}:8181/protected/v1/dailyReport/1546376400000
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

###

GET http://{{host}}:8181/protected/v1/backup
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

###

GET http://{{host}}:8181/protected/v1/totalPercent/5d72a45aa6fd3f2514ccc5b0
Accept: */*
Authorization: Bearer {{auth_token}}
Cache-Control: no-cache
Content-Type: application/json

###